/**
 * SQL Writer
 *
 * Generates a complete seed.sql file from curriculum data.
 * Outputs INSERT statements in FK order with ON CONFLICT DO NOTHING.
 */

import {
  PathwayDef,
  UnitDef,
  LessonDef,
  WordDef,
  RootDef,
  WordRootLink,
  FrequencyExampleDef,
  QuizQuestionDef,
} from '../curriculum';

function escapeSQL(str: string): string {
  return str.replace(/'/g, "''");
}

function sqlArray(arr: string[]): string {
  return `ARRAY[${arr.map((s) => `'${escapeSQL(s)}'`).join(', ')}]`;
}

function sqlNull(val: string | number | null | undefined): string {
  if (val === null || val === undefined) return 'NULL';
  if (typeof val === 'number') return String(val);
  return `'${escapeSQL(val)}'`;
}

function generatePathwaySQL(p: PathwayDef, totalWords: number, totalUnits: number): string {
  return `INSERT INTO public.pathways (id, name, slug, description, promise, total_words, total_units, preview_items, is_active)
VALUES (
  '${escapeSQL(p.id)}',
  '${escapeSQL(p.name)}',
  '${escapeSQL(p.slug)}',
  '${escapeSQL(p.description)}',
  '${escapeSQL(p.promise)}',
  ${totalWords},
  ${totalUnits},
  ARRAY[${p.preview_items.map((i) => `'${escapeSQL(i)}'`).join(', ')}],
  ${p.is_active}
)
ON CONFLICT (id) DO NOTHING;`;
}

function generateUnitSQL(u: UnitDef, wordCount: number): string {
  return `INSERT INTO public.units (id, pathway_id, name, description, "order", word_count)
VALUES (
  '${escapeSQL(u.id)}',
  '${escapeSQL(u.pathway_id)}',
  '${escapeSQL(u.name)}',
  '${escapeSQL(u.description)}',
  ${u.order},
  ${wordCount}
)
ON CONFLICT (id) DO NOTHING;`;
}

function generateLessonSQL(l: LessonDef, wordCount: number): string {
  return `INSERT INTO public.lessons (id, unit_id, name, "order", word_count, lesson_type)
VALUES (
  '${escapeSQL(l.id)}',
  '${escapeSQL(l.unit_id)}',
  '${escapeSQL(l.name)}',
  ${l.order},
  ${wordCount},
  '${escapeSQL(l.lesson_type)}'
)
ON CONFLICT (id) DO NOTHING;`;
}

function generateRootSQL(r: RootDef): string {
  return `  ('${escapeSQL(r.id)}', '${escapeSQL(r.letters)}', '${escapeSQL(r.meaning)}', '${escapeSQL(r.transliteration)}')`;
}

function generateWordSQL(w: WordDef): string {
  const freq = w.frequency !== undefined ? `, ${w.frequency}` : '';
  const desc = w.description !== undefined ? `, '${escapeSQL(w.description)}'` : '';
  const cols = w.frequency !== undefined
    ? 'id, lesson_id, arabic, transliteration, meaning, audio_url, "order", frequency, description'
    : 'id, lesson_id, arabic, transliteration, meaning, audio_url, "order"';

  return `  ('${escapeSQL(w.id)}', '${escapeSQL(w.lesson_id)}', '${escapeSQL(w.arabic)}', '${escapeSQL(w.transliteration)}', '${escapeSQL(w.meaning)}', ${sqlNull(w.audio_url)}, ${w.order}${freq}${desc})`;
}

function generateWordRootSQL(wr: WordRootLink): string {
  return `  ('${escapeSQL(wr.word_id)}', '${escapeSQL(wr.root_id)}')`;
}

function generateQuizSQL(q: QuizQuestionDef): string {
  return `  ('${escapeSQL(q.id)}', '${escapeSQL(q.lesson_id)}', '${escapeSQL(q.question)}', '${escapeSQL(q.correct_answer)}', ${sqlArray(q.wrong_answers)}, '${escapeSQL(q.explanation)}', ${q.order})`;
}

export function generateSeedSQL(
  pathway: PathwayDef,
  units: UnitDef[],
  lessons: LessonDef[],
  words: WordDef[],
  roots: RootDef[],
  wordRoots: WordRootLink[],
  frequencyExamples: FrequencyExampleDef[],
  quizQuestions: QuizQuestionDef[]
): string {
  const lines: string[] = [];
  const date = new Date().toISOString().split('T')[0];

  // Only include roots that are actually referenced
  const usedRootIds = new Set(wordRoots.map((wr) => wr.root_id));
  const usedRoots = roots.filter((r) => usedRootIds.has(r.id));

  // Calculate word counts
  const totalWords = words.length;
  const totalUnits = units.length;

  const unitWordCounts = new Map<string, number>();
  for (const unit of units) {
    const unitLessonIds = lessons
      .filter((l) => l.unit_id === unit.id)
      .map((l) => l.id);
    const count = words.filter((w) => unitLessonIds.includes(w.lesson_id)).length;
    unitWordCounts.set(unit.id, count);
  }

  const lessonWordCounts = new Map<string, number>();
  for (const lesson of lessons) {
    const count = words.filter((w) => w.lesson_id === lesson.id).length;
    lessonWordCounts.set(lesson.id, count);
  }

  // Header
  lines.push(`-- ============================================================`);
  lines.push(`-- Generated Seed Data: Salah First Pathway`);
  lines.push(`-- Generated by tools/seed-pipeline on ${date}`);
  lines.push(`-- Total: ${totalWords} words, ${units.length} units, ${lessons.length} lessons`);
  lines.push(`-- ============================================================`);
  lines.push('');

  // Pathway
  lines.push(`-- ============================================================`);
  lines.push(`-- Pathway: ${pathway.name}`);
  lines.push(`-- ============================================================`);
  lines.push(generatePathwaySQL(pathway, totalWords, totalUnits));
  lines.push('');

  // Units
  lines.push(`-- ============================================================`);
  lines.push(`-- Units (${units.length})`);
  lines.push(`-- ============================================================`);
  for (const unit of units) {
    lines.push(generateUnitSQL(unit, unitWordCounts.get(unit.id) || 0));
    lines.push('');
  }

  // Lessons
  lines.push(`-- ============================================================`);
  lines.push(`-- Lessons (${lessons.length})`);
  lines.push(`-- ============================================================`);
  for (const lesson of lessons) {
    const wc = lesson.lesson_type === 'root' ? 0 : (lessonWordCounts.get(lesson.id) || 0);
    lines.push(generateLessonSQL(lesson, wc));
    lines.push('');
  }

  // Roots
  lines.push(`-- ============================================================`);
  lines.push(`-- Roots (${usedRoots.length})`);
  lines.push(`-- ============================================================`);
  lines.push(`INSERT INTO public.roots (id, letters, meaning, transliteration) VALUES`);
  lines.push(usedRoots.map(generateRootSQL).join(',\n'));
  lines.push(`ON CONFLICT (id) DO NOTHING;`);
  lines.push('');

  // Words — group by lesson for readability
  lines.push(`-- ============================================================`);
  lines.push(`-- Words (${words.length})`);
  lines.push(`-- ============================================================`);

  const wordLessons = lessons.filter((l) => l.lesson_type === 'word' || l.lesson_type === 'frequency');
  for (const lesson of wordLessons) {
    const lessonWords = words.filter((w) => w.lesson_id === lesson.id);
    if (lessonWords.length === 0) continue;

    const hasFrequency = lessonWords.some((w) => w.frequency !== undefined);
    const cols = hasFrequency
      ? 'id, lesson_id, arabic, transliteration, meaning, audio_url, "order", frequency, description'
      : 'id, lesson_id, arabic, transliteration, meaning, audio_url, "order"';

    lines.push(`-- ${lesson.name}`);
    lines.push(`INSERT INTO public.words (${cols}) VALUES`);
    lines.push(lessonWords.map(generateWordSQL).join(',\n'));
    lines.push(`ON CONFLICT (id) DO NOTHING;`);
    lines.push('');
  }

  // Word-Root Links
  lines.push(`-- ============================================================`);
  lines.push(`-- Word-Root Links (${wordRoots.length})`);
  lines.push(`-- ============================================================`);
  lines.push(`INSERT INTO public.word_roots (word_id, root_id) VALUES`);
  lines.push(wordRoots.map(generateWordRootSQL).join(',\n'));
  lines.push(`ON CONFLICT (word_id, root_id) DO NOTHING;`);
  lines.push('');

  // Frequency Examples (if any)
  if (frequencyExamples.length > 0) {
    lines.push(`-- ============================================================`);
    lines.push(`-- Frequency Word Examples (${frequencyExamples.length})`);
    lines.push(`-- ============================================================`);
    lines.push(
      `INSERT INTO public.frequency_word_examples (id, word_id, arabic, transliteration, meaning, audio_url, "order") VALUES`
    );
    lines.push(
      frequencyExamples
        .map(
          (f) =>
            `  ('${escapeSQL(f.id)}', '${escapeSQL(f.word_id)}', '${escapeSQL(f.arabic)}', '${escapeSQL(f.transliteration)}', '${escapeSQL(f.meaning)}', ${sqlNull(f.audio_url)}, ${f.order})`
        )
        .join(',\n')
    );
    lines.push(`ON CONFLICT (id) DO NOTHING;`);
    lines.push('');
  }

  // Quiz Questions
  lines.push(`-- ============================================================`);
  lines.push(`-- Quiz Questions (${quizQuestions.length})`);
  lines.push(`-- ============================================================`);
  // Group by lesson
  const quizByLesson = new Map<string, QuizQuestionDef[]>();
  for (const q of quizQuestions) {
    if (!quizByLesson.has(q.lesson_id)) quizByLesson.set(q.lesson_id, []);
    quizByLesson.get(q.lesson_id)!.push(q);
  }

  for (const [lessonId, qs] of quizByLesson) {
    const lesson = lessons.find((l) => l.id === lessonId);
    lines.push(`-- Quiz: ${lesson?.name || lessonId}`);
    lines.push(
      `INSERT INTO public.lesson_quiz_questions (id, lesson_id, question, correct_answer, wrong_answers, explanation, "order") VALUES`
    );
    lines.push(qs.map(generateQuizSQL).join(',\n'));
    lines.push(`ON CONFLICT (id) DO NOTHING;`);
    lines.push('');
  }

  // High Frequency Pathway (preserved from existing seed)
  lines.push(`-- ============================================================`);
  lines.push(`-- High Frequency Pathway (preserved from original seed)`);
  lines.push(`-- ============================================================`);
  lines.push(HIGH_FREQUENCY_PATHWAY_SQL);

  return lines.join('\n');
}

// Preserved from existing seed.sql
const HIGH_FREQUENCY_PATHWAY_SQL = `
INSERT INTO public.pathways (id, name, slug, description, promise, total_words, total_units, preview_items, is_active)
VALUES (
  'high-frequency',
  'High Frequency',
  'high-frequency',
  '80% of Quranic vocabulary.',
  'Learn the most common words in the Quran',
  50,
  1,
  ARRAY['وَ', 'فِي', 'مِن'],
  true
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.units (id, pathway_id, name, description, "order", word_count)
VALUES (
  'hf-u1-particles',
  'high-frequency',
  'Common Particles',
  'The most frequently occurring particles in the Quran',
  1,
  3
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.lessons (id, unit_id, name, "order", word_count, lesson_type)
VALUES
  ('hf-u1-l1-wa',  'hf-u1-particles', 'The Connector: Wa',  1, 1, 'frequency'),
  ('hf-u1-l2-fi',  'hf-u1-particles', 'The Vessel: Fi',     2, 1, 'frequency'),
  ('hf-u1-l3-min', 'hf-u1-particles', 'The Origin: Min',    3, 1, 'frequency')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.words (id, lesson_id, arabic, transliteration, meaning, "order", frequency, description)
VALUES
  ('w-wa',  'hf-u1-l1-wa',  'وَ',  'Wa',  'And',   1, 9800,
   'The most common particle. It connects ideas, stories, and blessings.'),
  ('w-fi',  'hf-u1-l2-fi',  'فِي', 'Fi',  'In',    1, 3200,
   'Places things within context. Where something exists or occurs.'),
  ('w-min', 'hf-u1-l3-min', 'مِن', 'Min', 'From',  1, 3000,
   'Indicates origin, source, and the beginning of journeys.')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.frequency_word_examples (id, word_id, arabic, transliteration, meaning, "order")
VALUES
  ('fex-wa-1', 'w-wa', 'وَالشَّمْسِ',  'Wash-shams',    'And the sun',       1),
  ('fex-wa-2', 'w-wa', 'وَالْقَمَرِ',  'Wal-qamar',     'And the moon',      2),
  ('fex-wa-3', 'w-wa', 'وَالنَّهَارِ', 'Wan-nahar',     'And the day',       3),
  ('fex-fi-1', 'w-fi', 'فِي الْأَرْضِ',  'Fil-ard',       'In the earth',      1),
  ('fex-fi-2', 'w-fi', 'فِي السَّمَاءِ',  'Fis-samaa',     'In the sky',        2),
  ('fex-fi-3', 'w-fi', 'فِي قُلُوبِهِمْ',  'Fi quloobihim', 'In their hearts',   3),
  ('fex-min-1', 'w-min', 'مِنَ السَّمَاءِ', 'Minas-samaa',   'From the sky',      1),
  ('fex-min-2', 'w-min', 'مِن رَبِّكَ',    'Min rabbik',    'From your Lord',    2),
  ('fex-min-3', 'w-min', 'مِنَ النَّاسِ',  'Minan-naas',    'From mankind',      3)
ON CONFLICT (id) DO NOTHING;
`;
